- name: Deploy static website
  hosts: webservers
  become: true

  vars:
    domain_name: "szabogergely.com"
    email: "contact@szabogergely.com"

  tasks:
    - name: Install Ngnix, Certbot and Cloudflare plugin
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-dns-cloudflare
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy website files
      copy:
        src: ../dist/prod/
        dest: /var/www/szabogergely
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Copy Nginx site config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/szabogergely
      notify: Reload Nginx

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/szabogergely
        dest: /etc/nginx/sites-enabled/szabogergely
        state: link
      notify: Reload Nginx

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx

    - name: Create Cloudflare credentials file
      copy:
        dest: /etc/letsencrypt/cloudflare.ini
        mode: '0600'
        content: |
          dns_cloudflare_api_token = {{ cloudflare_api_token }}

    - name: Obtain certificate via DNS challenge
      command: >
        certbot certonly
        --dns-cloudflare
        --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
        --non-interactive
        --agree-tos
        --email {{ email }}
        -d {{ domain_name }}
        -d *.{{ domain_name }}
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem

    - name: Ensure certbot renewal timer is enabled
      systemd:
        name: certbot.timer
        enabled: yes
        state: started

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
